name: CI

on:
  push:
    branches: [master]
  pull_request: ~
  workflow_dispatch: ~

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v3
      - uses: actions/setup-go@v6
        with:
          # TODO: The version of golangci-lint we use is not compatible with Go 1.26+, migrate to new version
          go-version: '1.25'
      - name: Lint project
        run: just install lint
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.16', '1.17', '1.18', '1.19', '1.20', '1.21', '1.22', '1.23', '1.24', '1.25', '1.26']
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v3
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: run tests
        run: EASYPOST_TEST_API_KEY=123 EASYPOST_PROD_API_KEY=123 just install test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v3
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - name: Run tests
        run: EASYPOST_TEST_API_KEY=123 EASYPOST_PROD_API_KEY=123 just install coverage
      - name: Coverage
        if: github.ref == 'refs/heads/master'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
